=== Marcoscardozogit/ciarte-web/.astro/collections/settings.schema.json
{
  "$ref": "#/definitions/settings",
  "definitions": {
    "settings": {
      "type": "object",
      "properties": {
        "nombre": {
          "type": "string"
        },
        "whatsapp": {
          "type": "string"
        },
        "direccion": {
          "type": "string"
        },
        "maps_link": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "facebook": {
          "type": "string"
        },
        "facebook2": {
          "type": "string"
        },
        "instagram": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "nombre",
        "whatsapp",
        "direccion",
        "email"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== Marcoscardozogit/ciarte-web/src/content/settings/site.json
{
    "nombre": "CIArte – El Laberinto",
    "whatsapp": "3874535157",
    "direccion": "Ruta Nacional 11, a Campo Santo Entre Laprida, Entre Ríos y, A4430 Gral. Güemes, Salta",
    "email": "contacto@ciarte.com.ar",
    "facebook": "https://facebook.com/ellaberintoteatro",
    "instagram": "https://instagram.com/ciarte_guemes"
}
